const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const els=new Map(),storage=new Map(),blobs=[];
function el(){return {style:{},dataset:{},classList:{toggle(){},remove(){},add(){}},innerHTML:'',value:'',checked:true,clientWidth:1000,clientHeight:700,scrollWidth:1000,scrollHeight:700,focus(){},setSelectionRange(){},addEventListener(){},setAttribute(){},append(){},replaceChildren(){},click(){},remove(){},querySelector(){return null;},getBoundingClientRect(){return {width:1000,height:700}}};}
const ctx={console,Blob,Date,Math,JSON,Set,Map,Promise,setTimeout,clearTimeout,requestAnimationFrame:f=>f(),localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{documentElement:{dataset:{}},getElementById:id=>{if(!els.has(id))els.set(id,el());return els.get(id)},querySelectorAll:()=>[],querySelector:()=>null,createElement:()=>el(),addEventListener(){}},URL:{createObjectURL:b=>{blobs.push(b);return 'blob:test'},revokeObjectURL(){}},fetch:async()=>({json:async()=>({configured:false})})};
ctx.confirm=()=>true;ctx.window=ctx;ctx.addEventListener=()=>{};ctx.scrollTo=()=>{};vm.createContext(ctx);
for(const f of ['storage.js','quality.js','app.js','workbench.js','homepage.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../public',f),'utf8'),ctx);
(async()=>{await vm.runInContext('loadDemo()',ctx);assert.ok(els.get('bpmn-svg-wrapper').innerHTML.includes('<svg'));assert.ok(els.get('onepager-content').innerHTML.includes('Prozessziele'));assert.ok(storage.has('bpmn:index'));const id=JSON.parse(storage.get('bpmn:index'))[0].id;await vm.runInContext(`loadProcess(${JSON.stringify(id)})`,ctx);assert.equal(vm.runInContext('currentLogicCore.processName',ctx),'Service Request Management');vm.runInContext('exportBpmnXml()',ctx);fs.writeFileSync(require('node:path').join(require('node:os').tmpdir(),'process-studio-demo.bpmn'),await blobs.at(-1).text());vm.runInContext('exportConfluence()',ctx);fs.writeFileSync(require('node:path').join(require('node:os').tmpdir(),'process-studio-confluence.xml'),await blobs.at(-1).text());await vm.runInContext(`setMode('migrate');document.getElementById('legacy-input').value='Basisinformationen\\nService Request\\nProzessüberblick\\nStandardaufträge bearbeiten.\\nProzessziel\\nEffiziente Erfüllung\\nProzessschritte\\nAuftrag prüfen und umsetzen.';previewLegacy()`,ctx);assert.ok(els.get('migration-content').innerHTML.includes('Standardaufträge'));await vm.runInContext("openWorkspace('migrate')",ctx);assert.equal(els.get('block-free').style.display,'none');assert.equal(els.get('free-examples').hidden,true);assert.equal(els.get('back-home').hidden,false);assert.equal(els.get('workspace-title').textContent,'Bestehenden Prozess überführen');vm.runInContext('showHome()',ctx);assert.equal(els.get('workspace').hidden,true);assert.equal(els.get('workspace-heading').hidden,true);vm.runInContext("openWorkspace('free')",ctx);assert.equal(els.get('block-migrate').style.display,'none');assert.equal(els.get('workspace-title').textContent,'Neuen Prozess-Onepager erstellen');await vm.runInContext('loadDemo()',ctx);
const initial=vm.runInContext('JSON.stringify(currentLogicCore)',ctx);
vm.runInContext("selectedNodeId='a';openNodeEditor();document.getElementById('node-label').value='Auftrag sorgfältig prüfen'",ctx);
await vm.runInContext('saveNodeEdit()',ctx);assert.equal(vm.runInContext('documentsStale',ctx),true);
await vm.runInContext('undoModel()',ctx);assert.equal(vm.runInContext('JSON.stringify(currentLogicCore)',ctx),initial);assert.equal(vm.runInContext('documentsStale',ctx),false);
vm.runInContext('exportWorkingCopy()',ctx);const backup=await blobs.at(-1).text();ctx.backupFile={size:backup.length,text:async()=>backup};
await vm.runInContext('resetAll();importWorkingCopy(backupFile)',ctx);
assert.equal(vm.runInContext('JSON.stringify(currentLogicCore)',ctx),initial);
assert.equal(vm.runInContext('currentOnepager.scope',ctx),JSON.parse(backup).onepager.scope);
assert.ok(vm.runInContext("lastLayout.edgeRoutes.f5.length >= 4",ctx));
assert.throws(()=>vm.runInContext(`safeParseJSON('{"nodes":[', 'test')`,ctx));
fs.writeFileSync(require('node:path').join(require('node:os').tmpdir(),'process-studio-qa.svg'),vm.runInContext('currentBpmnXml',ctx));
console.log('PASS: navigation, persistence, BPMN/Confluence, migration parser, node edit, undo, complete working-copy round trip, loop routes and strict JSON. DOM harness; no visual browser QA.');})().catch(e=>{console.error(e);process.exit(1)});
